// import Footer from "./components/Footer/Footer";
// import Navbar from "./components/Navbar/Navbar";
// import ToastProvider from "./components/Shared/TosterProvider";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import ToastProvider from "./components/Shared/TosterProvider";
import "./globals.css";

export const metadata = {
  title: "Ashik Hasan",
  description: "Generated by Ashik Hasan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` font-sans antialiased`}>
        <div className="bg-[#0F0F0F] text-white w-full min-h-screen">
          <div className="max-w-7xl mx-auto">
            <Navbar />
            <div className="container mx-auto px-0 font-sans">
              {children}
              <ToastProvider />
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
